import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Separator from "@/components/Separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
        <Navbar />
        <Separator />
        <div className="mb-2 w-full h-1"></div>
        {children}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
