import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Separator from "@/components/Separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "विध्या Vibes",
  description: "Generated by create next app",
};

// NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_bG9naWNhbC1lZWwtMi5jbGVyay5hY2NvdW50cy5kZXYk
// CLERK_SECRET_KEY=sk_test_S3Yr6Yw0myzzhelVNe3FDeB5fzzYZF1dT0ndh3GvuN

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
        <Navbar />
        <Separator />
        <div className="mb-2 w-full h-1"></div>
        {children}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
